name: Deploy sitio estático

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v3

    - name: Limpiar carpeta remota antes de subir
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: rm -rf ${{ secrets.SSH_TARGET_PATH }}/*

    - name: Instalar dependencias
      run: npm install

    - name: Construir sitio
      run: npm run build

    - name: Copiar archivos al servidor
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "dist/*"
        target: ${{ secrets.SSH_TARGET_PATH }}
        strip_components: 1
        overwrite: true
